{% set name = "dnspython" %}
{% set version = "2.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8dcfae8c7460a2f84b4072e26f1c9f4101ca20c071649cb7c34e8b6a93d58984

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - poetry
  run:
    - python >=3.6
    - idna >=2.1
    - cryptography >=2.6
    - httpcore
    - sniffio

test:
  imports:
    - dns
    - dns.rdtypes
    - dns.rdtypes.ANY
    - dns.rdtypes.IN
    - dns.rdtypes.CH
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.dnspython.org
  summary: DNS toolkit
  license: ISC
  license_file: LICENSE
  license_family: OTHER
  dev_url: https://github.com/rthalley/dnspython
  doc_url: http://www.dnspython.org

extra:
  recipe-maintainers:
    - synapticarbors
    - jan-janssen
