{% set name = "dnspython" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 224e32b03eb46be70e12ef6d64e0be123a64e621ab4c0822ff6d450d52a540b9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - poetry
  run:
    - python >=3.6
    - idna >=2.1
    - cryptography >=2.6

test:
  imports:
    - dns
    - dns.rdtypes
    - dns.rdtypes.ANY
    - dns.rdtypes.IN
    - dns.rdtypes.CH
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.dnspython.org
  summary: DNS toolkit
  license: ISC
  license_file: LICENSE
  license_family: OTHER
  dev_url: https://github.com/rthalley/dnspython
  doc_url: http://www.dnspython.org

extra:
  recipe-maintainers:
    - synapticarbors
    - jan-janssen
