{% set name = "dnspython" %}
{% set version = "2.0.0" %}
{% set bundle = "zip" %}
{% set hash = "044af09374469c3a39eeea1a146e8cac27daec951f1f1f157b1962fc7cb9d1b7" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  noarch: python
  number: {{ build }}
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - idna >=2.1
    - pycryptodome
    - ecdsa >=0.13

test:
  imports:
    - dns
    - dns.rdtypes
    - dns.rdtypes.ANY
    - dns.rdtypes.IN

about:
  home: http://www.dnspython.org
  summary: DNS toolkit
  license: ISC
  license_file: LICENSE
  license_family: OTHER
  dev_url: https://github.com/rthalley/dnspython
  doc_url: http://www.dnspython.org

extra:
  recipe-maintainers:
    - pmlandwehr
