{% set name = "dnspython" %}
{% set version = "2.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a0034815a59ba9ae888946be7ccca8f7c157b286f8455b379c692efb51022a15

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8.0,<4.0.0
    - pip
    - poetry-core
    - hatchling
  run:
    - python >=3.8.0,<4.0.0
    - idna >=2.1,<4.0
    - cryptography >=2.6,<42.0
    - httpcore >=0.17.3
    - sniffio
  run_constrained:
    - httpx >=0.24.1
    - h2 >=4.1.0
    - trio >=0.14,<0.23
    - wmi >=1.5.1,<2.0.0
    - aioquic >=0.9.20

test:
  imports:
    - dns
    - dns.rdtypes
    - dns.rdtypes.ANY
    - dns.rdtypes.IN
    - dns.rdtypes.CH
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.dnspython.org
  summary: DNS toolkit
  license: ISC
  license_file: LICENSE
  license_family: OTHER
  dev_url: https://github.com/rthalley/dnspython
  doc_url: http://www.dnspython.org

extra:
  recipe-maintainers:
    - synapticarbors
    - jan-janssen
    - xylar
