{% set name = "dnspython" %}
{% set version = "2.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ce9c432eda0dc91cf618a5cedf1a4e142651196bbcd2c80e89ed5a907e5cfaf1

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling >=1.21.0
  run:
    - python >={{ python_min }},<4.0.0
    - sniffio
  run_constrained:
    - aioquic >=1.0.0
    - cryptography >=43
    - httpcore >=1.0.0
    - httpx >=0.26.0
    - h2 >=4.1.0
    - idna >=3.7
    - trio >=0.23
    - wmi >=1.5.1

test:
  imports:
    - dns
    - dns.rdtypes
    - dns.rdtypes.ANY
    - dns.rdtypes.IN
    - dns.rdtypes.CH
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://www.dnspython.org
  summary: DNS toolkit
  license: ISC
  license_file: LICENSE
  license_family: OTHER
  dev_url: https://github.com/rthalley/dnspython
  doc_url: http://www.dnspython.org

extra:
  recipe-maintainers:
    - synapticarbors
    - jan-janssen
    - xylar
