schema_version: 1

context:
  version: 2.9.0

package:
  name: dnspython
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/d/dnspython/dnspython-${{ version }}.tar.gz
  sha256: b44dc6b18f07a8b1c56676a19fbfdb5209415b046a9cece286baafa87ff3f7f1

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - uv-build >=0.9.21,<0.13.0
  run:
    - python >=${{ python_min }},<4.0.0
  run_constraints:
    - aioquic >=1.3.0
    - cryptography >=50
    - httpcore >=2.13
    - httpx >=2.13
    - h2 >=4.4
    - idna >=3.20
    - trio >=0.34
    - wmi >=1.5.1

tests:
  - python:
      imports:
        - dns
        - dns.rdtypes
        - dns.rdtypes.ANY
        - dns.rdtypes.IN
        - dns.rdtypes.CH
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - '*'

about:
  summary: DNS toolkit
  license: ISC
  # Local copy of license until https://github.com/rthalley/dnspython/pull/1335 is merged and new release
  license_file: LICENSE
  homepage: http://www.dnspython.org
  repository: https://github.com/rthalley/dnspython
  documentation: http://www.dnspython.org

extra:
  recipe-maintainers:
    - synapticarbors
    - jan-janssen
    - xylar
