travis:
  secure:
    BINSTAR_TOKEN: JuvFdHxD3iiaATGvpZK7ISb0hIGf0OFpZOK0WvxRIMVj1mofLK8yAhiP4zBv+ED5PlTRZQCn+yivl4xFIo1zRDF+JJKwAFrldbwwk7xrev1kYp+15Dt/aF6ItN7l8f/SSg7BRn+xuKjjNeJsWZ6enIKMT7KU4qqsnWYDKLJBUO0uF5lE4B5GlzCDskHhDSuHLWmipcyQgG81kr3WtdvN4/5GqAZ79KXzEvWUknVbjfGXj4QrIUMWMerYPWzxieX+xtInc2EV7v64mS8QclXDg0kbOMU5BgW2k6e9wPC2kXukJwfsfcmPBdUvjD+4QPAzIkYfMM5HZCpU8afajtlKhie8YOpQdGc+hbT0oK8e4XeEMvxkmDL4H1sBlRggmK+a5SB8/QRbqgx5ahYTbdzkWqal9qBqUzwxSZKVSMlCf976Uev9juDmsaES5Zh4I3w3eo2egaemZ55XLmyqZ6IYoLRT8s+iFghTXcuq94w+qrO6jIHcEqKUHkoeHoUJ9nfN4GtZUpQGDtU+3WBbQZfptZeGXvRSD/tut/biikLm6yxvFGPO4Z3pk0/jpC/AZHCmnrPguGwsYwGp9uyt4QognKH722L0T9iDC6c6tRgN8fuepBfFBxgl/za3YKs5nlrUkNEIJzmv+ltjKr95iI1LVGpAmDm+yKHc1sjPVorelOQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
