travis:
  secure:
    BINSTAR_TOKEN: HLLW16Ew4XbprXVwrKImq2cMXMPJiE1YWqjEBeh7LlxL25rYqelSuVXxRzGho4LYYZbRzAnUqw259yC6qvxEKu32yDa9PpOgAvg1n5zyo7ghGSeFLbvELMbhpmeKBodAJfR4eza3E7EyaP28ijLpd1opcCEi2CgISfFq1Xp36nNzDgN8HLdAxMko2wsE0uXFDOR3OHPbXfiLqOak08kTVkifdCAYFomXsYPMPC3EfXRGL0apmedyqm8f6VAlaeHwkZ5xbQJoc2pFmPZ692GZa461TVyPsSFS9jRF1KJieFGnIpOWY2pTOA6eL3p1LzCrwoD8XhC3/jxRSz61l0Z98hQDfCtIM63PMbvO6RwW48ARvCUtQEz2bAWL3g60D1XLHyQXacDDFpP0raB9Ff9alpN6/ot0b5jjQYcEx3p9s6svtlOGxe2G05/tWigHBVthGj+wZL1oBskND6l4BrmoUSntsGMJEKdseCKq8mMNq6mQ8fT8JDmwp9U7mpM2Cw1Tz32jzTw91dlQg35K70F11JZEKBs00AaEO6fKOujdtTznRS90wkoxsTTlpxDWSTi2W+22aWuo53Tlg+BYW7OPicy4ZlTSTL9h2fVpU9GXgcpOZVjKsl92swGBNHAciZM0DvyA0V5XNipBQASZkEebyYvt+15jE3KDeMVyTy7+RLQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
